image: randr0id/android-docker

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

stages:
  - test
  - build

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle 
  - chmod +x ./gradlew

lint_test:
  stage: test
  except:
    - tags
  tags:
    - docker
  artifacts:
    when: always
    expire_in: 6 months
    paths:
      - rxloader/build/reports/
  script:
    - ./gradlew lintRelease

release_build:
  stage: build
  only:
    - schedules
    - web
    - rx1
  tags:
    - docker
  artifacts:
    expire_in: 1 year
    paths:
      - rxloader/build/outputs/aar/
      - rxloader/build/publications/aar/
  script:
    - ./gradlew generatePomFileForAarPublication
    - ./gradlew assembleRelease

merge_build:
  stage: build
  except:
    - schedules
    - web
    - tags
    - rx1
  tags:
    - docker
  script:
    - ./gradlew assembleRelease
